version: "3.8"

services:
  backend:
    build: ./server
    container_name: codeide-backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/workspaces:/app/workspaces
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongo:27017/codeide
      - JWT_SECRET=supersecret123
      - GITHUB_CLIENT_ID=your_dummy_id
      - GITHUB_CLIENT_SECRET=your_dummy_secret
    depends_on:
      - mongo

  frontend:
    build: ./client/code_ide
    container_name: codeide-frontend
    ports:
      - "3000:5173"
    volumes:
      - ./client/code_ide:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  mongo:
    image: mongo
    container_name: codeide-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

